[project]
name = "arthur"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.1",
    "firebase-admin>=7.1.0",
    "uvicorn[standard]>=0.30.0",
]
